/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class creditcloud_com_myndkjnidemo_MyJni */

#ifndef _Included_creditcloud_com_myndkjnidemo_MyJni
#define _Included_creditcloud_com_myndkjnidemo_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     creditcloud_com_myndkjnidemo_MyJni
 * Method:    print
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_creditcloud_com_myndkjnidemo_MyJni_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
